### ISSUE TITLE
Android build failing: Could not find method kotlinOptions()

### ISSUE THREAD

**Issue by benmarsh** [braze-inc/braze-cordova-sdk#91]
Hi,

I'm getting the following error when adding the Braze Cordova SDK to a Capacitor project.

```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/ben/Code/cap-5-test/node_modules/braze-cordova-sdk/src/android/build-extras.gradle' line: 28

* What went wrong:
A problem occurred evaluating script.
> Could not find method kotlinOptions() for arguments [build_extras_f3s7x5xace2nhpapu2c5nbnj7$_run_closure3$_closure4$_closure5@40cb30f2] on extension 'android' of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.
```

Steps to reproduce;
- Create a brand new Ionic/Capacitor project `ionic start`
- Add Android platform and run `npx cap sync`
- Build in Android Studio - works
- Add Braze Cordova SDK to package.json `"braze-cordova-sdk": "github:braze-inc/braze-cordova-sdk#master"`
- Run `npm install` and then `npx cap sync` again to pull in SDK
- Build in Android Studio - fails with the above error.

This is with Gradle 8.0.2 and braze-cordova-sdk 7.0.0

**Comment by radixdev** [comment]
Hello @benmarsh ,

You'll need to import kotlin into your ionic app. This will likely need to be done in your top level `build.gradle` file.

**Comment by benmarsh** [comment]
Finally came back to this upgrade - thanks for the above hint, that worked well. Interestingly it threw up a new problem, but it is different so I will raise a new issue for that.

Just for completeness and to help anyone looking at this in future, I added the following:

`/build.gradle`

- directly below “apply plugin: 'com.android.application'” at top of file

```groovy
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
```

`/android/build.gradle`

- add classpath to dependencies and optionally version at top of buildscript block
- 1.8.20 is used elsewhere in other Capacitor plugins

```groovy
buildscript {
	ext.kotlin_version = project.hasProperty("kotlin_version") ? rootProject.ext.kotlin_version : '1.8.20'
	. . .
	dependencies {
		. . .
		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"	
	}
}
```
