### ISSUE TITLE
app is crashing with SDK version 2.33.0

### ISSUE THREAD

**Issue by asifcbh** [braze-inc/braze-cordova-sdk#92]
Hey team, 
I am trying upgrade to braze-cordova-sdk version 2.33.0, and while building the app it fails with the following error 
`This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSUserTrackingUsageDescription key with a string value explaining to the user how the app uses this data.`

we don't want to enable ad targeting for our users hence I have set the preference  to    "com.appboy.ios_enable_idfa_automatic_collection": "no"

But it fails with the same error.

**Comment by jerielng** [comment]
Hi @asifcbh, this was resolved in version [3.0.0](https://github.com/braze-inc/braze-cordova-sdk/releases/tag/3.0.0) with the automatic dependency on App Tracking Transparency being removed. Could you upgrade to that version instead?

**Comment by asifcbh** [comment]
I think it worked. 
Thanyou

**Comment by asifcbh** [comment]
Thankyou for the quick help @jerielng, I worked this time.
